### ISSUE TITLE
Todo: Implement this correctly. It's currently only a dummy.

### ISSUE THREAD

**Issue by SeppPenner** [SeppPenner/NetCoreMQTTExampleIdentityConfig#2]

**Comment by SeppPenner** [comment]
It's not a dummy anymore, but still has some error with the password hasher?!

**Comment by SeppPenner** [comment]
- [x] Add logging correctly
- [x] Generate correct ToString() for DTOs and classes to have the possibility to log data
- [x] Add MQTT specific stuff
- [x] Add methods to add / remove claims to / from user
- [x] Check how it's best to use the claims (One claim per user with text values? Or one claim per MQTT topic restriction?)
- [x] Support clientIdPrefix

**Comment by SeppPenner** [comment]
Done.
